#' Gene list pathway analysis by hypergeometric test
#' 
#' Run pathway analysis (hypergeometric test) for gene list. Wrapper function for hypergeoTestForGeneset.
#' @param glist List of query genes. (DEG list)
#' @param refgmt Reference gene set list. (Pathway set in list form)
#' @param tglist List of background gene space, same length as glist.
#' @param ncore Number of cores to use.
#' @return List of enricher Object: up, down
#' @export


Gen_enrichment <- function(glist, refgmt, tglist, ncore=1, ef.psc=0) {
	require(parallel)
	bgspace <- unique(unlist(refgmt))
	glist <- lapply(glist, function(gg) intersect(gg, bgspace))

	if(ncore <= 1) {
		enrobj <- lapply(names(glist), function(aid) hypergeoTestForGeneset(glist[[aid]], refgmt, tglist[[aid]], ef.psc=ef.psc) )
	}
	if(ncore > 1) {
		enrobj <- lapply(names(glist), function(aid) hypergeoTestForGeneset2(glist[[aid]], refgmt, tglist[[aid]], ncore=ncore, ef.psc=ef.psc) )
	}
	enrobj <- lapply(enrobj, function(hgeos) {
		pv <- ifelse(hgeos$int == 0, NA, hgeos$pVal)
		hgeos$qVal <- p.adjust(pv, method='fdr')
		hgeos$qVal <- ifelse(hgeos$int == 0, 1, hgeos$qVal)
		hgeos$logQ <- -log10(hgeos$qVal)
		return(hgeos)
		})
	names(enrobj) <- names(glist)
	return(enrobj)
}


#' Enrichment object list to matrix
#' 
#' Turn enrichment object list (generated by ClusterProfiler enricher or Gen_enrichment) into matrix of needed value for drawing heatmap.
#' @param enrobj Enrichment result list.
#' @param val.col Column to output.
#' @param log Log transform? (used if p value is outputted)
#' @return List of enricher Object: up, down
#' @export


enrobj2Matrix <- function(enrobj, val.col='pvalue', log=TRUE) {
	LS <- lapply(names(enrobj), function(set) {
		dff <- data.frame(enrobj[[set]])
		if('Description' %in% names(dff)) dff <- dff %>% dplyr::rename(termID=ID, ID=Description)
		dff$set <- set
		dff <- dff[order(dff$set),]
		return(dff)
	})
	hmplot <- do.call(rbind, LS)

	# detect log values
	is_log <- FALSE
	if(any(quantile(hmplot[,val.col], na.rm=TRUE) > 1)) is_log <- TRUE
	if(log & is_log) cat('val.col is already in log values.'); log <- FALSE
	if(log & !is_log) {
		hmplot$logV <- -log10(hmplot[,val.col])
		plotMat <- reshape2::acast(hmplot, ID~set, value.var=logV, fill = NA)
	}

	if(!log) plotMat <- reshape2::acast(hmplot, ID~set, value.var=val.col, fill = NA)
	plotMat <- plotMat[order(apply(plotMat,1, sum, na.rm=TRUE), decreasing=TRUE),]
	return(plotMat)
}




