#' Gene list pathway analysis by hypergeometric test
#'
#' Run pathway analysis (hypergeometric test) for gene list. Wrapper function for hypergeoTestForGeneset.
#' @param glist List of query genes. (DEG list)
#' @param refgmt Reference gene set list. (Pathway set in list form)
#' @param tglist List of background gene space, same length as glist.
#' @param minGeneSet Minimum number of genes in gene set. Default 10.
#' @param ncore Number of cores to use.
#' @param ef.psc Pseudocount option for calculating enrichment factors. Default 0.
#' @return List of enricher Object: up, down
#' @export

glist_enrichment <- function(
	glist, refgmt, tglist, minGeneSet = 10, ncore = 1, ef.psc = 0
) {
	bgspace <- unique(unlist(refgmt))
	glist  <- lapply(glist,  \(gg) intersect(gg, bgspace))
	tglist <- lapply(tglist, \(gg) intersect(gg, bgspace))

	if (ncore > 1 && !requireNamespace("parallel", quietly = TRUE)) {
		warning("Package 'parallel' is not available. Falling back to single-core processing.", call. = FALSE)
		ncore <- 1
	}

	if (ncore > 1) {
		enrobj <- parallel::mclapply(names(glist), function(aid) {
			hypergeoTestForGeneset(glist[[aid]], refgmt, tglist[[aid]], minGeneSet, ef.psc = ef.psc)
		}, mc.cores = ncore)
	} else {
		enrobj <- lapply(names(glist), function(aid) {
			hypergeoTestForGeneset(glist[[aid]], refgmt, tglist[[aid]], minGeneSet, ef.psc = ef.psc)
		})
	}
	names(enrobj) <- names(glist)
	enrobj
}

#' @rdname glist_enrichment
#' @export
Gen_enrichment <- function(
	glist, refgmt, tglist, minGeneSet = 10, ncore = 1, ef.psc = 0
) {
	.Deprecated("glist_enrichment", "Use glist_enrichment instead.")
	glist_enrichment(glist, refgmt, tglist, minGeneSet, ncore, ef.psc)
}


#' Enrichment object list to matrix
#'
#' Turn enrichment object list (generated by ClusterProfiler enricher or Gen_enrichment) into matrix of needed value for drawing heatmap.
#' @param enrobj Enrichment result list.
#' @param val.col Column to output.
#' @param log Should the output be log10 transformed? (used if p value is input)
#' @return List of enricher Object: up, down
#' @importFrom dplyr rename
#' @importFrom reshape2 acast
#' @export

enrobj2Matrix <- function(enrobj, val.col = "pvalue", log = TRUE) {
	LS <- lapply(names(enrobj), function(set) {
		dff <- data.frame(enrobj[[set]])
		if ("Description" %in% names(dff)) {
			dff <- dff |> dplyr::rename("termID" = "ID", "ID" = "Description")
		}
		dff$set <- set
		dff[order(dff$set), ]
	})

	hmplot <- do.call(rbind, LS)

	# detect log values
	is_log <- FALSE
	if (any(quantile(hmplot[, val.col], na.rm = TRUE) > 1)) {
		is_log <- TRUE
	}
	if (log & is_log) {
		message("val.col seems to already be in log values. Setting log = FALSE.")
	}

	log <- FALSE
	if (log & !is_log) {
		hmplot$logV <- -log10(hmplot[, val.col])
		plotMat <- reshape2::acast(hmplot, ID ~ set, value.var = "logV", fill = NA)
	}

	if (!log) {
		plotMat <- reshape2::acast(hmplot, ID ~ set, value.var = val.col, fill = NA)
	}
	plotMat <- plotMat[order(apply(plotMat, 1, sum, na.rm = TRUE), decreasing = TRUE), ]

	plotMat
}
